cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "AdoptOpenJDK/openjdk"

brew "readline"
brew "sqlite"
brew "xz"
brew "python"
brew "awscli"
brew "crf++"
brew "mecab"
brew "mecab-ipadic"
brew "cabocha"
brew "curl"
brew "docker"
brew "fzf"
brew "ghq"
brew "git"
brew "git-secrets"
brew "lua"
brew "hugo"
brew "mas"
brew "nkf"
brew "node"
brew "nodebrew"
brew "octave"
brew "openssl"
brew "php@7.4"
brew "composer"
brew "postgresql"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "ruby"
brew "tig"
brew "tmux"
brew "tfenv"
brew "tree"
brew "vim"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "adoptopenjdk11"
cask "alfred"
cask "android-platform-tools"
cask "blackhole"
cask "clipy"
cask "docker"
cask "font-hackgen"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "slack"
cask "spectacle"
cask "openinterminal-lite"
cask "visual-studio-code"
cask "xmind"
cask "xquartz"

mas "XCode", id: 497799835
mas "Slac", id: 803453959
mas "LadioCast", id: 411213048
